// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PiratesBay.Data;

namespace PiratesBay.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PiratesBay.Models.CommunicationLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataEntryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CommunicationLog");
                });

            modelBuilder.Entity("PiratesBay.Models.CorrectiveMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MessageType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Parameter")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CorrectiveMessage");
                });

            modelBuilder.Entity("PiratesBay.Models.Device_info", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Area")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Device_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GUID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Latitude")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Longitude")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mac_Id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Device_info");
                });

            modelBuilder.Entity("PiratesBay.Models.EventLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DataEntryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErrorLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MessageType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EventLog");
                });

            modelBuilder.Entity("PiratesBay.Models.ParameterMeasureMarkAmber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Ammonium_level_High")
                        .HasColumnType("float");

                    b.Property<double>("Ammonium_level_Low")
                        .HasColumnType("float");

                    b.Property<double>("Dissolved_oxygen_High")
                        .HasColumnType("float");

                    b.Property<double>("Dissolved_oxygen_Low")
                        .HasColumnType("float");

                    b.Property<double>("PH_Level_High")
                        .HasColumnType("float");

                    b.Property<double>("PH_Level_Low")
                        .HasColumnType("float");

                    b.Property<double>("Salinity_High")
                        .HasColumnType("float");

                    b.Property<double>("Salinity_Low")
                        .HasColumnType("float");

                    b.Property<double>("Total_Dissolved_Solid_High")
                        .HasColumnType("float");

                    b.Property<double>("Total_Dissolved_Solid_Low")
                        .HasColumnType("float");

                    b.Property<double>("Water_Temperature_High")
                        .HasColumnType("float");

                    b.Property<double>("Water_Temperature_Low")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("ParameterMeasureMarkAmber");
                });

            modelBuilder.Entity("PiratesBay.Models.ParameterMeasureMarkGreen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Ammonium_level_High")
                        .HasColumnType("float");

                    b.Property<double>("Ammonium_level_Low")
                        .HasColumnType("float");

                    b.Property<double>("Dissolved_oxygen_High")
                        .HasColumnType("float");

                    b.Property<double>("Dissolved_oxygen_Low")
                        .HasColumnType("float");

                    b.Property<double>("PH_Level_High")
                        .HasColumnType("float");

                    b.Property<double>("PH_Level_Low")
                        .HasColumnType("float");

                    b.Property<double>("Salinity_High")
                        .HasColumnType("float");

                    b.Property<double>("Salinity_Low")
                        .HasColumnType("float");

                    b.Property<double>("Total_Dissolved_Solid_High")
                        .HasColumnType("float");

                    b.Property<double>("Total_Dissolved_Solid_Low")
                        .HasColumnType("float");

                    b.Property<double>("Water_Temperature_High")
                        .HasColumnType("float");

                    b.Property<double>("Water_Temperature_Low")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("ParameterMeasureMarkGreen");
                });

            modelBuilder.Entity("PiratesBay.Models.ParameterMeasureMarkRed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Ammonium_level_High")
                        .HasColumnType("float");

                    b.Property<double>("Ammonium_level_Low")
                        .HasColumnType("float");

                    b.Property<double>("Dissolved_oxygen_High")
                        .HasColumnType("float");

                    b.Property<double>("Dissolved_oxygen_Low")
                        .HasColumnType("float");

                    b.Property<double>("PH_Level_High")
                        .HasColumnType("float");

                    b.Property<double>("PH_Level_Low")
                        .HasColumnType("float");

                    b.Property<double>("Salinity_High")
                        .HasColumnType("float");

                    b.Property<double>("Salinity_Low")
                        .HasColumnType("float");

                    b.Property<double>("Total_Dissolved_Solid_High")
                        .HasColumnType("float");

                    b.Property<double>("Total_Dissolved_Solid_Low")
                        .HasColumnType("float");

                    b.Property<double>("Water_Temperature_High")
                        .HasColumnType("float");

                    b.Property<double>("Water_Temperature_Low")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("ParameterMeasureMarkRed");
                });

            modelBuilder.Entity("PiratesBay.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("RoleName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("PiratesBay.Models.SensorData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Ammonium_level")
                        .HasColumnType("float");

                    b.Property<DateTime>("DataEntryTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Device_Id")
                        .HasColumnType("int");

                    b.Property<double>("Dissolved_oxygen")
                        .HasColumnType("float");

                    b.Property<double>("PH_Level")
                        .HasColumnType("float");

                    b.Property<double>("Salinity")
                        .HasColumnType("float");

                    b.Property<double>("Total_Dissolved_Solid")
                        .HasColumnType("float");

                    b.Property<double>("Water_Temperature")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("Device_Id");

                    b.ToTable("SensorData");
                });

            modelBuilder.Entity("PiratesBay.Models.UserInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AlternativePhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Device_Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Device_Id");

                    b.HasIndex("Role_Id");

                    b.ToTable("UserInfo");
                });

            modelBuilder.Entity("PiratesBay.Models.Value", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Values");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Value 100"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Value 106"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Value 102"
                        });
                });

            modelBuilder.Entity("PiratesBay.Models.SensorData", b =>
                {
                    b.HasOne("PiratesBay.Models.Device_info", "Device_Info")
                        .WithMany()
                        .HasForeignKey("Device_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PiratesBay.Models.UserInfo", b =>
                {
                    b.HasOne("PiratesBay.Models.Device_info", "Device_Info")
                        .WithMany()
                        .HasForeignKey("Device_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PiratesBay.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("Role_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
