// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PiratesBay.Data;

namespace PiratesBay.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5");

            modelBuilder.Entity("PiratesBay.Models.CommunicationLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Communication_Type")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataEntryTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT");

                    b.Property<int>("User_Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("warning_corrective_mapping_ID")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("User_Id");

                    b.HasIndex("warning_corrective_mapping_ID");

                    b.ToTable("CommunicationLog");
                });

            modelBuilder.Entity("PiratesBay.Models.CorrectiveMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Amber_Threshold_High")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Amber_Threshold_Low")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Green_Threshold_High")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Green_Threshold_Low")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MessageType")
                        .HasColumnType("TEXT");

                    b.Property<string>("Red_Threshold_High")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Red_Threshold_Low")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("lastupdatedby")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("lastupdatedon")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CorrectiveMessage");
                });

            modelBuilder.Entity("PiratesBay.Models.Device_info", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Area")
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<string>("Device_Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GUID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Latitude")
                        .HasColumnType("TEXT");

                    b.Property<string>("Longitude")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mac_Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("lastupdatedby")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("lastupdatedon")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Device_info");
                });

            modelBuilder.Entity("PiratesBay.Models.EventLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataEntryTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("Device_Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT");

                    b.Property<string>("MessageType")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Device_Id");

                    b.ToTable("EventLog");
                });

            modelBuilder.Entity("PiratesBay.Models.ParameterBenchmark", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Amber_Threshold_High")
                        .HasColumnType("REAL");

                    b.Property<double>("Amber_Threshold_Low")
                        .HasColumnType("REAL");

                    b.Property<double>("Green_Threshold_High")
                        .HasColumnType("REAL");

                    b.Property<double>("Green_Threshold_Low")
                        .HasColumnType("REAL");

                    b.Property<int>("Param_Id")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Red_Threshold_High")
                        .HasColumnType("REAL");

                    b.Property<double>("Red_Threshold_Low")
                        .HasColumnType("REAL");

                    b.Property<string>("lastupdatedby")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("lastupdatedon")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Param_Id");

                    b.ToTable("ParameterBenchmark");
                });

            modelBuilder.Entity("PiratesBay.Models.Parameter_Master", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("TEXT");

                    b.Property<string>("Param_Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("lastupdatedby")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("lastupdatedon")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Parameter_Masters");
                });

            modelBuilder.Entity("PiratesBay.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("RoleName")
                        .HasColumnType("TEXT");

                    b.Property<string>("lastupdatedby")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("lastupdatedon")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("PiratesBay.Models.SensorData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataEntryTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("Device_Id")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Input_Value")
                        .HasColumnType("REAL");

                    b.Property<int>("Param_Id")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Device_Id");

                    b.HasIndex("Param_Id");

                    b.ToTable("SensorData");
                });

            modelBuilder.Entity("PiratesBay.Models.UserDeviceMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Device_Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("User_Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("lastupdatedby")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("lastupdatedon")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UserDeviceMapping");
                });

            modelBuilder.Entity("PiratesBay.Models.UserInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AlternativePhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("NotificationFrequency")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<int>("Role_Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("lastupdatedby")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("lastupdatedon")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Role_Id");

                    b.ToTable("UserInfo");
                });

            modelBuilder.Entity("PiratesBay.Models.Value", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Values");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Value 100"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Value 106"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Value 102"
                        });
                });

            modelBuilder.Entity("PiratesBay.Models.Warning_Corrective_Mapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CorrectiveMessage_ID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Warning_ID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("lastupdatedby")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("lastupdatedon")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Warning_Corrective_Mapping");
                });

            modelBuilder.Entity("PiratesBay.Models.CommunicationLog", b =>
                {
                    b.HasOne("PiratesBay.Models.UserInfo", "UserInfo")
                        .WithMany()
                        .HasForeignKey("User_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PiratesBay.Models.Warning_Corrective_Mapping", "Warning_Corrective_Mapping")
                        .WithMany()
                        .HasForeignKey("warning_corrective_mapping_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PiratesBay.Models.EventLog", b =>
                {
                    b.HasOne("PiratesBay.Models.Device_info", "Device_Info")
                        .WithMany()
                        .HasForeignKey("Device_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PiratesBay.Models.ParameterBenchmark", b =>
                {
                    b.HasOne("PiratesBay.Models.Parameter_Master", "Parameter_Master")
                        .WithMany()
                        .HasForeignKey("Param_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PiratesBay.Models.SensorData", b =>
                {
                    b.HasOne("PiratesBay.Models.Device_info", "Device_Info")
                        .WithMany()
                        .HasForeignKey("Device_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PiratesBay.Models.Parameter_Master", "Parameter_Master")
                        .WithMany()
                        .HasForeignKey("Param_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PiratesBay.Models.UserInfo", b =>
                {
                    b.HasOne("PiratesBay.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("Role_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
